sudo: required
language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_SDKS=android-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a ANDROID_TRAVIS=1
  global:
    - secure: ulG1uHCmHbfo3yn6bDAPzoCAgkxo6rxrO/UA6UqY2/5lQIhQEWi8Y1H7PANu/ublEbUO2sgSRop9TI/FoMX3EQRqDxS5Rfatkz2bTrABHmbLjR5VutWksVUxYY1Nu/TDHCKtttz5hlbWD8F6HpuEuGm5ZvOlZPHUfpkk4VDsGZg3SywP8Y6ftrq4N5qu80pj+MHGRe7p72jWpcRNaxGJm2Ym5hIrJsmNktyje1GPVyDx/fDPglIo+SxlkXhQ6UD6me8igCXMw5TsM1D3m+SRox7oac0/eEQOemqAooTbkwa9j0QhZUyaclP8n+Lj044u0cyQp3XuasPGTzpO61BlQF8WMgG1XsiumP9OrDr/WOyPgGi5l1QswHqlKqubsdH/OqMhxcFIQ60MFNlJnoPeTMjw3/2S9ifJhwibFdHLWsXPMl+dV2GxRd0Uv6PuF1Wkfb5Ls3fJ6Upg0KCI4NAvCFunMjC2vqzKtlCc3xTicm8KKxuM6I5sP92EkObRvVNvcyLUxeZM93pdxcY19itPeY9CUv8UEqNHZZGPFC2+tx7rN5syWqh/UG8eUgIIpbK/LNQkuxebMZ5z2ptVQ+nh+ZMTigqIkd29s1s44et0SsCAwwxnp4Rz7r9WeuTsj4F/Gced+bytH5+cpyJOxadmt3YApbVvo/ZAbKv1saBUabw=

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod +x ./ci/wait_for_emulator
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew createDebugCoverageReport coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    tags: true
